version: '3'
services:
  db:
    image: nouchka/sqlite3
    volumes:
      - ./tmp/db:/var/lib/sqlite3/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/tutorial_ruby_on_rails
    ports:
      - "3000:3000"
    depends_on:
      - db